export default [
    {
        imagem: `${require('../assets/capas/harry_potter.png')}`,
        titulo: 'Harry Potter e a Criança Amaldiçoada',
        original: 'Harry Potter and the Cursed Child',
        genero: 'Infanto Juvenil',
        faixaEtaria: '12 anos',
        classificacao: [1,2,3,4,5],
        autor: 'J.K Rowling',
        origem: 'Inglaterra',
        descricao: 'Sempre foi difícil ser Harry Potter e não é mais fácil agora que ele é um sobrecarregado funcionário do Ministério da Magia, marido e pai de três crianças em idade escolar. Enquanto Harry lida com um passado que se recusa a ficar para trás, seu filho mais novo, Alvo, deve lutar com o peso de um legado de família que ele nunca quis. À medida que passado e presente se fundem de forma ameaçadora, ambos, pai e filho, aprendem uma incômoda verdade: às vezes as trevas vêm de lugares inesperados.\n',
        previa: 'Tenha acesso ao primeiro capítulo do livro por tempo determinado e aproveite sua experiência',
        preco: '25,90',
        comprar: 'https://www.amazon.com.br/Harry-Potter-Crian%C3%A7a-Amaldi%C3%A7oada-Parte/dp/8532530435'
    },
    {
        imagem: `${require('../assets/capas/cidade_ossos.jpg')}`,
        titulo: 'Cidade dos Ossos',
        original: 'City Of Bones',
        genero: 'Fantasia urbana, Ficção juvenil, Literatura fantástica, Ficção de aventura',
        faixaEtaria: '16 anos',
        classificacao: [1,2,3,4],
        autor: 'Cassandra Clare',
        origem: 'Estados Unidos',
        descricao: 'O primeiro volume da série best-seller Os Instrumentos Mortais, de Cassandra Clare Depois ser apresentada ao Mundo de Sombras e a Jace ― um Caçador que tem a aparência de um anjo, mas a língua tão afiada quanto Lúcifer ―, Clary Fray só queria que sua vida voltasse ao normal. Mas o que é “normal” quando você é uma Caçadora de Sombras assassina de demônios, sua mãe está em um coma magicamente induzido e você de repente descobre que criaturas como lobisomens, vampiros e fadas realmente existem? Para complicar ainda mais, alguém na cidade de Nova York está matando jovens do Submundo. Quando o segundo dos Instrumentos Mortais, a Espada da Alma, é roubada, a aterrorizante Inquisidora chega ao Instituto para investigar ― e suas suspeitas caem diretamente sobre Jace. Como Clary pode impedir os planos malignos de Valentim se Jace está disposto a trair tudo aquilo em que acredita para ajudar o pai? Nessa sequência de tirar o fôlego da série Os Instrumentos Mortais, Cassandra Clare atrai os leitores de volta para o lado mais obscuro do submundo de Nova York, onde amar nunca é seguro e o poder se torna a mais mortal das tentações.',
        previa: 'Tenha acesso ao primeiro capítulo do livro por tempo determinado e aproveite sua experiência',
        preco: '26,99',
        comprar: 'https://www.amazon.com.br/Cidade-ossos-Vol-1-instrumentos-mortais/dp/8501087149?tag=kns00-20&ascsubtag=go_952006559_46722488349_301325114817_aud-594374058437:dsa-412640848944_c_29042468855',
    },
    {
        imagem: `${require('../assets/capas/harry_potter_prisioneiro.jpg')}`,
        titulo: 'Harry Potter e o Prisioneiro de Askaban',
        original: 'Harry Potter and the Prisoner of Azkaban',
        genero: 'Infanto Juvenil',
        faixaEtaria: '14 anos',
        classificacao: [1,2,3,4],
        autor: 'J.K Rowling',
        origem: 'Inglaterra',
        descricao: 'As aulas estão de volta à Hogwarts e Harry Potter não vê a hora de embarcar no expresso a vapor que o levará de volta à escola de bruxaria. Mais uma vez suas férias na rua dos Alfeneiros foi triste e solitária. Com muita ação, humor e magia, \'Harry Potter e o prisioneiro de Azkaban\' traz de volta o gigante atrapalhado Rúbeo Hagrid, o sábio diretor Alvo Dumbledore, a exigente professora de transformação Minerva MacGonagall e o novo mestre Lupin, que guarda grandes surpresas para Harry.',
        previa: 'Tenha acesso ao primeiro capítulo do livro por tempo determinado e aproveite sua experiência',
        preco: '30,20',
        comprar: 'https://www.amazon.com.br/Harry-Potter-Prisioneiro-Azkaban-Rowling/dp/8532512062/ref=sr_1_1?hvadid=330144803228&hvdev=c&hvlocphy=1032132&hvnetw=g&hvpos=1t1&hvqmt=e&hvrand=7833611876316304999&hvtargid=kwd-341738522577&keywords=harry+potter+prisioneiro+de+azkaban&qid=1555858157&s=gateway&sr=8-1',
    },
    {
        imagem: `${require('../assets/capas/harry_potter_reliquias.jpg')}`,
        titulo: 'Harry Potter e as Reliquias da Morte',
        original: 'Harry Potter and the Deathly Hallows',
        genero: 'Infanto Juvenil',
        faixaEtaria: '14 anos',
        classificacao: [1,2,3,4,5],
        autor: 'J.K Rowling',
        origem: 'Inglaterra',
        descricao: 'Harry, que acabou de completar 16 anos, parte rumo ao sexto ano na Escola de Magia e Bruxaria de Hogwarts, animado e, ao mesmo tempo, apreensivo com a perspectiva de ter aulas particulares com o professor Dumbledore, o diretor da escola e o bruxo mais respeitado em toda comunidade mágica. Harry, longe de ser aquele menino magricela que vivia no quarto debaixo da escada na casa dos tios trouxas, é um dos principais nomes entre aqueles que lutam contra Voldemort, e se vê cada vez mais isolado à medida em que os rumores de que ele é O Eleito, o único capaz de derrotar o Lorde das Trevas, se espalham pelo mundo bruxo. Dois atentados contra a vida de estudantes, a certeza de Harry quanto ao envolvimento de Draco Malfoy com os Comensais da Morte e o comportamento de Snape, suspeito como sempre, adicionam ainda mais tensão ao já inquietante período. Apesar de tudo isso, ele e os amigos são adolescentes típicos: dividem tarefas escolares e dormitórios bagunçados, correm das aulas para os treinos de quadribol, e namoram. Rony e Hermione, os melhores amigos de Harry, se dão conta (finalmente!) da atração que sentem um pelo outro; Harry e a Gina, a irmã mais nova de Rony, também. Muitas peças do intricado quebra-cabeça criado por JK Rowling começam a se encaixar, à medida em que a escritora começa a preparar Harry (e os leitores) para o desfecho da série. Informações são reveladas por meio do uso da Penseira, um objeto que permite compartilhar memórias, utilizado por Harry e o professor Dumbledore para viajar no tempo, e por diferentes lugares, em busca de explicações sobre o passado de Voldemort. O final de Harry Potter e o enigma do Príncipe é de parar o coração. Mais uma vez, somos testemunhas da habilidade singular de Jo - como a criadora da série gosta de ser chamada - em misturar, num mesmo caldeirão, literatura, mitologia, folclore e religião. Este livro é mais desafiador que os anteriores, mas os leitores irão devorá-lo com igual voracidade e voltarão a inundar a Editora Rocco com perguntas sobre o final da saga. Alguém tem alguma dúvida sobre qual será o lançamento literário mais aguardado daqui por diante?',
        previa: 'Tenha acesso ao primeiro capítulo do livro por tempo determinado e aproveite sua experiência',
        preco: '32,99',
        comprar: 'https://www.amazon.com.br/Harry-Potter-As-Rel%C3%ADquias-Morte/dp/8532522610?tag=goog0ef-20&smid=A1ZZFT5FULY4LN&ascsubtag=go_726685122_51601401518_242574450465_pla-434266643485_c_',
    }
]